version: '2'

services:
  db:
    build: container/db
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  webapi:
    build: container/webapi
    ports:
      - 3000:3000
    links:
      - db
    environment:
      - API_PORT=3000
      - DB_URI=db
      - DB_PORT=27017
      - NODE_ENV=production
